//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub mod prelude;

pub mod artist;
pub mod genre;
pub mod playlist;
pub mod playlist_item;
pub mod publisher;
pub mod release;
pub mod track;
pub mod track_location;
